kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-access
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-access
subjects:
- kind: Group
  namespace: web
  name: groupObjectId

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: poi-access
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-access
subjects:
- kind: Group
  namespace: api
  name: groupObjectId
