kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-access
subjects:
- kind: Group
  namespace: web
  name: 6901f5d0-378c-413a-8310-fa73e2045d36

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-access
subjects:
- kind: Group
  namespace: api
  name: af27cdbb-1f1b-41e2-8e68-5125641dfec4
